# Generated by Django 3.0.4 on 2020-04-03 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_vacancy'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='salary',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
